#!/bin/bash



PROGNAME=`basename $0`
PROGPATH=`echo $0 | /bin/sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1.0.0.1 $' | sed -e 's/[^0-9.]//g'`


STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

print_version(){
	echo "$PROGNAME $REVISION"
}
print_usage() {
        echo "Usage: $PROGNAME [-U Jenkins URL] [-H hostname]"
        echo "		-U	Jenkins URL"
        echo "		-H	Hostname"
        echo ""
        echo "Usage: $PROGNAME --help"
        echo "Usage: $PROGNAME --version"
}

print_help() {
        print_version
        echo ""
        echo "Nagios Plugin to check state of a Jenkins Node via the Jenkins API"
        echo ""
        print_usage
        echo ""
        echo "$PROGNAME. © Jason Rivers 2025"
        echo ""
        exit 0
}


while getopts aH:U:h:v OPT
do
  case "$OPT" in
    H) NODENAME="$OPTARG" ;;
    U) JENKINS_URL="$OPTARG" ;;
    h) print_help
       exit "$STATE_UNKNOWN" ;;
    v) print_version
       exit "$STATE_UNKNOWN";;
   esac
done

if [ "x" = "x$JENKINS_URL" ]; then
    echo No Jenkins URL 
    print_help
    exit $STATE_CRITICAL
fi

if [ "x" = "x$NODENAME" ]; then
    echo No Node to check
    print_help
    exit $STATE_CRITICAL
fi

# Get the Jenkins Node State

URL=${JENKINS_URL}/computer/${NODENAME}/api/json 
JSON=$(curl -s -o - ${URL})

if ! echo $JSON | jq . > /dev/null 2>&1 ; then
    echo "UNKNOWN: Unable to read JSON Data"
    exit $STATE_UNKNOWN
fi

if [ "x" != "x$JSON" ]; then

    OFFLINE_STATUS=$(echo $JSON | jq .offline)

    case $OFFLINE_STATUS in

        "true")
            if [ "$(echo $JSON | jq -r .offlineCauseReason)" = "Offline because computer was idle; it will be relaunched when needed." ]; then
                ECODE=$STATE_OK
                MSG="OK: $(echo $JSON | jq -r .offlineCauseReason)"
            else
                ECODE=$STATE_CRITICAL
                MSG="CRITICAL: Node Offline! Reason: $(echo $JSON | jq -r .offlineCauseReason)"
            fi
            ;;
        "false")
            ECODE=$STATE_OK
            MSG="OK: Node Online"
            ;;
    esac

    echo $MSG
    exit $ECODE

fi

echo "UNKNOWN: Empty JSON Response from Jenkins"
exit $STATE_UNKNOWN
